import Head from "next/head";
import { useState } from "react";
import hexSorter from "hexsorter";
// const colorArray = ["#cccccc", "#dddddd", "#eeeeee", "#ffffff", "#000000"];
// const mostBright = hexSorter.sortColors(colorArray, "mostBrightColor");

export default function Home() {
  const [state, setState] = useState({ value: "", colorArray: [] });
  const createColorArray = (string) => {
    return string.split(/\r\n|\r|\n/);
  };
  const sortByBrightness = (array) => {
    return hexSorter.sortColors(array, "mostBrightColor");
  };
  const handleChange = (e) => {
    setState({ value: e.target.value });
  };
  const handleClick = (e) => {
    e.preventDefault();
    const colors = createColorArray(state.value).filter(
      (element) => element.length > 1
    );
    // const isBeginSharp = (currentValue) => {
    //   return currentValue.charAt(0) === "#";
    // };
    const is3Digits = (string) => {
      return string.length === 3 + 1;
    };
    const convert3to6 = (string3Digits) => {
      const sixLetters = [...string3Digits.replace("#", "")].map((element) => {
        return element.repeat(2);
      });
      return ["#", ...sixLetters].join("");
    };

    const formatted = colors.map((element) => {
      return is3Digits(element) ? convert3to6(element) : element;
    });

    setState({ ...state, colorArray: sortByBrightness(formatted) });
  };
  return (
    <div>
      <Head>
        <title>Hex color sorter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <textarea onChange={handleChange} rows="10" cols="50" />
        <button onClick={handleClick}>sort</button>
        <div>
          <code>{state.value}</code>
        </div>
        <div>
          <code>{state.colorArray}</code>
        </div>
        {/* <div>
          <code>{colorArray}</code>
        </div>
        <div>
          <code>{mostBright}</code>
        </div> */}
      </main>
    </div>
  );
}
